spring:
  application:
    name: journalApp
  data:
    mongodb:
      database: journaldb
      auto-index-creation: true
      uri: mongodb+srv://shadanhussain2004:Rwxnk3irTb4rJzGh@cluster0.byua8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  main:
    allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /journal

weather:
  api:
    key: 46bb8a9c73f1bb9759e29006adfa5dfe
