spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: hussainshadan2004@gmail.com
    password: asdg shpz ekkf xflb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#  data:
#    redis:
#      host: localhost
#      port: 6379

  redis:
    uri: redis-cli -u redis://default:xIHYb8OzkysQKyKcuX9I0HojsZEXJ9z0@redis-16987.c212.ap-south-1-1.ec2.redns.redis-cloud.com:16987

